config/routes.rb
Rails.application.routes.draw do
  
  resources :posts do 
    get 'lolposts' , on: :collection
    get 'valorantposts' , on: :collection
    get 'warzoneposts' , on: :collection
  end

  resources :warzoneplayers
  resources :valorantplayers
  resources :lolplayers
  devise_for :users, controllers: {omniauth_callbacks: 'omniauth'}
  
  devise_scope :user do 
     match 'users/editfoto' => 'registration#editfoto', :via => [:get], :as => 'editfoto'
  end


  root 'home#index'
  get 'home/about'
  get 'home/profile'

  scope "admin" do
    get "users", to: "users#index"
    get "users/:id", to: "users#show", as: "user"
    delete "users/:id", to: "users#destroy"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  
  def about
  end

  def profile
	@lolplayers= Lolplayer.find_by(user_id: current_user.id)
	@valorantplayers= Valorantplayer.find_by(user_id: current_user.id)
	@warzoneplayers= Warzoneplayer.find_by(user_id: current_user.id)  	
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_footer.html.erb
<footer class="container">
    <p class="float-end"><a href="#">Back to top</a></p>
    <p>© 2020-2021 FindMates. · <%= link_to 'About us', home_about_path %>  </p>
  </footer>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
	<div class="container-fluid">
	  <%= link_to root_path do %>
	  	<%= image_tag 'logo_white.png', size:"178x40" %>
	  <% end %>
	  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
	    <span class="navbar-toggler-icon"></span>
	  </button>
	  <div class="collapse navbar-collapse" id="navbarCollapse">
	    <ul class="navbar-nav me-auto mb-2 mb-md-0">
	      <li class="nav-item active">
	        <%= link_to "Post", posts_path, class:"nav-link" %>
	      </li>
          <li class="nav-item">
	        <%= link_to "LeagueOfLegends", lolposts_posts_path, class:"nav-link" %>
	      </li>
	      <li class="nav-item">
	        <%= link_to "Valorant", valorantposts_posts_path, class:"nav-link" %>
	      </li>
	      <li class="nav-item">
	        <%= link_to "Call of Duty Warzone", warzoneposts_posts_path, class:"nav-link" %>
	      </li>
	    </ul>

	    <form class="d-flex">
	       <ul class="navbar-nav me-auto mb-2 mb-lg-0">
	          <% if user_signed_in? %>
		        <li class = "nav-item">
		        	<%= link_to "Profilo", home_profile_path, class:"nav-link" %>
		        </li>
		        <li class = "nav-item">
		        	<%= link_to "Esci", destroy_user_session_path, method: :delete, class:"nav-link" %>
		        </li>
		    <% else %>
		    	<li class = "nav-item">
	        		<%= link_to "Registrati", new_user_registration_path, class:"nav-link" %>
	        	</li>
	        	<li class = "nav-item">
	        		<%= link_to "Accedi", new_user_session_path, class:"nav-link" %>
	        	</li>
	        <% end %>

	        <% if user_signed_in? && current_user.admin? %>
	        	<li class = "nav-item dropdown ">
					  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
					    Menù Admin
					  </a>

					  <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
					  	<li class>
					    	<%= link_to "Utenti", users_path, class:"nav-link dropdown-item bg-dark" %>
					    </li>

					    <li class>
					    	<%= link_to "LOL players", lolplayers_path, class:"nav-link dropdown-item bg-dark" %>
					    </li>
					    	
					    <li>
					    	<%= link_to "Valorant players", valorantplayers_path, class:"nav-link dropdown-item bg-dark" %>
					    </li>

					    <li>
					    	<%= link_to "Warzone players", warzoneplayers_path, class:"nav-link dropdown-item bg-dark" %>
					    </li>

					  </ul>
	        	</li>
	        <% end %>
		  </ul>
	    </form>
	  </div>
	</div>
</nav>

app/views/home/about.html.erb
<div class="card mb-3" style="max-width: 900px;">
  <div class="row g-0">
    <div class="col-md-4">
      <%= image_tag("Giampaolo.jpg", size: "525x350", :alt => "Immagine di Giampaolo")%>
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title text-end">Giampaolo Fabiani</h5>
        <p class="card-text text-end">Ingegneria Informatica</p>
        <p class="card-text text-end">Matricola: 1712037</p>
        <p class="card-text text-end">fabiani.1712037@studenti.uniroma1.it</p>
      </div>
    </div>
  </div>
</div>

<div class="card mb-3" style="max-width: 900px;">
  <div class="row g-0">
    <div class="col-md-4">
      <%= image_tag("Davide.jpg", size: "525x350", :alt => "Immagine di Giampaolo")%>
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title text-end">Davide Margottini</h5>
        <p class="card-text text-end">Ingegneria Informatica</p>
        <p class="card-text text-end">Matricola: 1762031</p>
        <p class="card-text text-end">margottini.1762031@studenti.uniroma1.it</p>
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<main>

 <!--3 Carousel -->
  <div id="myCarousel" class="carousel slide" data-bs-ride="carousel">
    <ol class="carousel-indicators">
      <li data-bs-target="#myCarousel" data-bs-slide-to="0" class="active"></li>
      <li data-bs-target="#myCarousel" data-bs-slide-to="1" class=""></li>
      <li data-bs-target="#myCarousel" data-bs-slide-to="2" class=""></li>
    </ol>
    <div class="carousel-inner">
      

      <div class="carousel-item active">
        <%= image_tag("awaken1.jpg", :alt => "Sfondo di LOL", class:"bd-placeholder-img", xmlns:"http://www.w3.org/2000/svg", preserveAspectRatio:"xMidYMid slice", focusable:"false" ) %>
        <div class="container">
          <div class="carousel-caption text-start">
            
          </div>
        </div>
      </div>

      <div class="carousel-item">
        <%= image_tag("valo1.jpg", :alt => "Sfondo di Valorant", class:"bd-placeholder-img", xmlns:"http://www.w3.org/2000/svg", preserveAspectRatio:"xMidYMid slice", focusable:"false" ) %>
        <div class="container">
          <div class="carousel-caption">
              <%= button_to "Vedi Post", posts_path, :method => :get, class:'btn btn-lg btn-primary' %>
            </p>
          </div>
        </div>
      </div>

      <div class="carousel-item">
        <%= image_tag("warzone1.jpg", :alt => "Sfondo fi warzone", class:"bd-placeholder-img", xmlns:"http://www.w3.org/2000/svg", preserveAspectRatio:"xMidYMid slice", focusable:"false" ) %>
        <div class="container">
          <div class="carousel-caption text-start">
            
              <%= button_to "Scrivi", new_post_path, :method => :get, class:'btn btn-lg btn-primary' %>
            </p>
          </div>
        </div>
      </div>

    </div>

    <a class="carousel-control-prev" href="#myCarousel" role="button" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </a>
    <a class="carousel-control-next" href="#myCarousel" role="button" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </a>
  </div>
  
  
  <div class= "container">
    <% if !user_signed_in? %>
        <div class="row">
          <div class="col-sm-6">
            <div class="card">
              <div class="card-body">
                <h2 class="card-title">Non sei registrato?</h2>
                <p class="card-text">Entra anche tu a far parte della nostra commiunity!</p>
                <%= button_to "Registrati", new_user_registration_path, :method => :get, class:'btn btn-lg btn-primary' %>
              </div>
            </div>
          </div>
          <div class="col-sm-6">
           <div class="card">
            <div class="card-body">
              <h2 class="card-title">Sei gia registrato?</h2>
              <p class="card-text">Entra nel sito e controlla se qualcuno vuole giocare con te!</p>
              <%= button_to "Log in", new_user_session_path, :method => :get, class:'btn btn-lg btn-primary' %>
            </div>
           </div>
          </div>
        </div>
  
    <%end %>

    <br />
  
    <div class="card text-center">
     <div class="card-body">
      <h1 class="card-title">Social</h1>
      <p class="card-text">Guarda la lista dei commenti principali per vedere se qualcuno cerca giocatori!</p>
      <p><%= button_to "vai ai post", posts_path, :method => :get, class:'btn btn-lg btn-primary' %> 
        <br />
        <%= button_to "Scrivi un nuovo Post", new_post_path, :method => :get, class:'btn btn-lg btn-primary' %>
      </p>
     </div>
    </div>
  </div>

  <br />

  <!--3 GIOCHI -->
  <div class="container marketing">
    <div class="card-group">
    
      <div class="card">
        <div class="card-body text-center">
          <p class="text-center">
          <%= image_tag("lol_logo.jpeg", size: "200x140", :alt => "Logo di LOL", class:"bd-placeholder-img", xmlns:"http://www.w3.org/2000/svg", preserveAspectRatio:"xMidYMid slice", focusable:"false" ) %>
          </p>
          <h3 class="card-title">League of Legends</h3>
          <p class="card-text">League of Legends è il famoso MOBA sviluppato da Riot Games®. Il gioco competitivo più giocato e seguito al mondo, scopri quante persone cercano un compagno nella landa degli evocatori</p>
          <p><%= button_to "Post di LeagueOfLegends", lolposts_posts_path, :method => :get, class:'btn btn-lg btn-primary' %></p>
        </div>
      </div>

      <div class="card">
        <div class="card-body text-center">
          <p class="text-center">
          <%= image_tag("valorant_logo.png", size: "200x140", :alt => "Logo di Valorant", class:"bd-placeholder-img", xmlns:"http://www.w3.org/2000/svg", preserveAspectRatio:"xMidYMid slice", focusable:"false" ) %>
          </p>
          <h3 class="card-title">Valorant</h3>
          <p class="card-text">Il nuovo FPS competitivo che sta spopolando in cerca di nuovi giocatori sia per partite amichevoli in compagnia che per cercare il tuo compagno perfetto di ranked</p>
          <p><%= button_to "Post di Valorant", valorantposts_posts_path, :method => :get, class:'btn btn-lg btn-primary' %></p>
        </div>
      </div>

      <div class="card">
        <div class="card-body text-center">
          <p class="text-center">
          <%= image_tag("call_logo2.png", size: "200x140", :alt => "Logo di Warzone", class:"bd-placeholder-img", xmlns:"http://www.w3.org/2000/svg", preserveAspectRatio:"xMidYMid slice", focusable:"false" ) %>  
          </p>
          <h3 class="card-title">Call of Duty Warzone</h3>
          <p class="card-text">Il Battle Royale ambientato nel mondo di Modern Warfare®. Prepara il paracadute per atterrare insieme a tanti nuovi amici con cui arrivare insieme alla vittoria finale</p>
          <p><%= button_to "Post di Warzone", warzoneposts_posts_path, :method => :get, class:'btn btn-lg btn-primary' %></p>
        </div>
      </div>

    </div>

  </div><!-- /.container -->
  <br /><br />
</main>

app/views/home/profile.html.erb
<div id="myCarousel" class="container carousel slide" data-bs-ride="carousel">
	<h1 class= "text-center">
  		Profilo
  		
	</h1>
        <p class="text-center"><%= current_user.email%></p>
        <p class="text-center">
        	<%= image_tag(current_user.avatar_thumbnail)%><br />
        <small>
          <%= link_to "Modifica immagine profilo", editfoto_path, class: "text-muted fs-6" %><br />
          <%= link_to "Modifica Dati Profilo",edit_user_registration_path, class: "text-muted fs-6" %>    
        </small>
        </p>


    <% if @lolplayers %>
    	<h4 class= "text"><%= image_tag("lolpost.jpeg", size: "35x35", :alt => "Logo di LOL") %>  LeagueofLegends </h4>
		<table class="table table-striped ">
      		<thead class= "table">
    			<tr>
      				<th scope="col">Nickname</th>
      				<th scope="col">Elo</th>
      				<th scope="col">Ruolo</th>
              <th scioe="col"></th>
    			</tr>
  			</thead>
  			<tbody>
		    <tr>
		      <td> <%= @lolplayers.nickname %> </td>
		      <td><%= @lolplayers.elo %></td>
		      <td><%= @lolplayers.ruolo %></td>
          <td><%= link_to "Modifica", edit_lolplayer_path(@lolplayers), class: "text-muted" %></td>
		    </tr>
		  </tbody>
		</table>
	<% end %>

  
	<% if @valorantplayers %><br />
    	<h4 class= "text"><%= image_tag("valopost.jpeg", size: "35x35", :alt => "Logo di LOL") %>  Valorant </h4>
		<table class="table table-striped">
      		<thead class= "table">
    			<tr>
      				<th scope="col">Nickname</th>
      				<th scope="col">Elo</th>
      				<th scope="col">Ruolo</th>
              <th scioe="col"></th>
    			</tr>
  			</thead>
  			<tbody>
		    <tr>
		      <td> <%= @valorantplayers.nickname %> </td>
		      <td><%= @valorantplayers.elo %></td>
		      <td><%= @valorantplayers.ruolo %></td>
          <td>
          <%= link_to "Modifica", edit_valorantplayer_path(@valorantplayers), class: "text-muted fs-6" %>
          </td>
		    </tr>
		  </tbody>
		</table>
	<% end %>


	<% if @warzoneplayers %><br />
    	<h4 class= "text"><%= image_tag("warzonepost.jpeg", size: "35x35", :alt => "Logo di LOL") %> CallOfDuty Warzone</h4>
		<table class="table table-striped">
      		<thead class= "table">
    			<tr>
      				<th scope="col">Nickname</th>
      				<th scope="col">Livello</th>
              <th></th>
    			</tr>
  			</thead>
  			<tbody>
		    <tr>
		      <td> <%= @warzoneplayers.nickname %> </td>
		      <td><%= @warzoneplayers.livello %></td>
          <td><%= link_to "Modifica", edit_warzoneplayer_path(@warzoneplayers), class: "text-muted fs-6" %></td>
		    </tr>
		  </tbody>
		</table>
	<% end %>
</div>



<hr/>
<div class="container marketing">
    <!-- Three columns of text below the carousel -->

    <div class="row">
      <% if !@lolplayers %>
      <div class="col-lg-4">
        <%= image_tag("lol_logo.jpeg", size: "200x140", :alt => "Logo di LOL", class:"bd-placeholder-img", xmlns:"http://www.w3.org/2000/svg", preserveAspectRatio:"xMidYMid slice", focusable:"false" ) %>
        
        <p>Inserisci i tuoi dati di LeagueOfLegends </p>
        <p><%= button_to "Vai", new_lolplayer_path, :method => :get, class:'btn btn-lg btn-secondary' %></p>
      </div><!-- /.col-lg-4 -->
      <% end %>

      <% if !@valorantplayers %>
      <div class="col-lg-4">
        <%= image_tag("valorant_logo.png", size: "200x140", :alt => "Logo di Valorant", class:"bd-placeholder-img", xmlns:"http://www.w3.org/2000/svg", preserveAspectRatio:"xMidYMid slice", focusable:"false" ) %>
        
        <p>Inserisci i tuoi dati di Valorant</p>
         <p><%= button_to "Vai", new_valorantplayer_path, :method => :get, class:'btn btn-lg btn-secondary' %></p>
      </div><!-- /.col-lg-4 -->
      <% end %>

      <% if !@warzoneplayers %>
      <div class="col-lg-4">
        <%= image_tag("call_logo2.png", size: "200x140", :alt => "Logo di Warzone", class:"bd-placeholder-img", xmlns:"http://www.w3.org/2000/svg", preserveAspectRatio:"xMidYMid slice", focusable:"false" ) %>

        
        <p>Inserisci i tuoi dati di Warzone</p>
        <p><%= button_to "Vai", new_warzoneplayer_path, :method => :get, class:'btn btn-lg btn-secondary' %></p>
      </div><!-- /.col-lg-4 -->
      <% end %>
    </div><!-- /.row -->

</div><!-- /.container -->
</div>